bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER') }}"
      dataset: airflow_refine_v2
      threads: 4
      location: asia-southeast2
