SELECT pt.statement_number                   AS statement_number,
       pt.transaction_id                     AS transaction_id,
       pt.sequence_number                    AS sequence_number,
       pt.finexus_user_id                    AS finexus_user_id,
       pt.principal_crn                      AS principal_crn,
       pt.own_crn                            AS own_crn,
       pt.updated_timestamp_dw009            AS updated_timestamp_dw009,
       pt.statement_month                    AS statement_month,
       pt.posted_date                        AS posted_date,
       pt.transaction_date                   AS transaction_date,
       ar.transaction_time                   AS transaction_time,
       pt.idr_transaction_amount             AS idr_transaction_amount,
       pt.original_transaction_amount        AS original_transaction_amount,
       pt.original_transaction_currency_code AS original_transaction_currency_code,
       pt.pos_mode_code                      AS pos_mode_code,
       pt.settled_amount                     AS settled_amount,
       pt.settled_currency_code              AS settled_currency_code,
       pt.commission_charge                  AS commission_charge,
       pt.cardholder_id_method_code          AS cardholder_id_method_code,
       pt.merchant_zip                       AS merchant_zip,
       pt.merchant_category_code             AS merchant_category_code,
       pt.merchant_id                        AS merchant_id,
       ar.merchant_name                      AS merchant_name,
       pt.approval_code                      AS approval_code,
       pt.adjustment_code                    AS adjustment_code,
       pt.transaction_code                   AS transaction_code,
       pt.transaction_description            AS transaction_description,
       pt.acquirer_reference_number          AS acquirer_reference_number,
       pt.pos_id                             AS pos_id,
       pt.issuer_currency                    AS issuer_currency,
       pt.acquirer_id                        AS acquirer_id,
       pt.ecom_indicator                     AS ecom_indicator,
       pt.payment_code                       AS payment_code,
       ar.status_code                        AS auth_status_code,
       ar.response_code                      AS auth_response_code,
       ar.approval_code                      AS auth_approval_code,
       ar.referral_code                      AS auth_referral_code,
       ar.transaction_type_code              AS auth_transaction_type_code,
       ar.transaction_type_code              AS auth_transaction_type_text,
       ar.pos_country_code                   AS pos_country_code,
       ar.additional_pos_info_code           AS additional_pos_info_code,
       ar.on_us_indicator                    AS on_us_indicator,
       ar.acquirer_institution_code          AS acquirer_institution_code,
       ar.fallback_txn_flag                  AS fallback_txn_flag,
       ar.contactless_flag                   AS contactless_flag,
       ar.charge_slip_flag                   AS charge_slip_flag,
       ar.surchurge_fee                      AS surchurge_fee,
       ar.surchurge_vat_fee                  AS surchurge_vat_fee,
       ar.issuer_surchurge_fee               AS issuer_surchurge_fee,
       ar.issuer_surchurge_vat_fee           AS issuer_surchurge_vat_fee,
       ar.routing_destination                AS routing_destination,
       ar.cvc_result_code                    AS cvc_result_code,
       ar.stand_in_flag                      AS stand_in_flag,
       ar.pin_status_code                    AS pin_status_code,
       tac.credit_indicator                  AS credit_indicator,
       tac.amount_type                       AS amount_type,
       tac.amount_type_desc                  AS amount_type_description
FROM `refine.posted_transactions` AS pt
         LEFT JOIN
     `refine.authorization_requests` AS ar
     ON
         ar.transaction_id = pt.transaction_id
         LEFT JOIN
     `mapping.transaction_adjustment_code` AS tac
     ON
             CAST(tac.transaction_code AS string) = CAST(pt.transaction_code AS string)
